### PR TITLE
take advantages of ldap rfc2307bis schema

### PR DESCRIPTION
**Pull request by osixia**
This aims to take advantage of ldap rfc2307bis posixGroup objectclass combined with groupOfUniqueNames objectclass to be able to use the ldap memberOf overlay.

if rfc2307bis posixGroup is not available, the behavior remain unchanged.

### CODE REVIEW

**Comment by neoclust** [comment]
:( i missed that some changes were from the stretch branch in this merge, i will look ho to fix this.

But thank you for the ldap-rfc2307bis-schema PR.

**Comment by osixia** [comment]
oops my bad sorry,
i totally forgot this pull request and merged a lot of other changed in the same branch.

**Comment by osixia** [comment]
maybe we can totaly reset that and i will make a cleaner request :)

**Comment by neoclust** [comment]
i look how to do this, will be saner :)

**Comment by neoclust** [comment]
revert done, you can redo PR, i will review and merge quickly

**Comment by neoclust** [comment]
btw, nothing related but you can come on irc #pulse-fr and/or #pulse-en   ( on freenode )

**Pull request merged**
